### ISSUE TITLE
Requirements File?

### ISSUE THREAD

**Issue by staniPetrox** [Thanos-DB/FullyConvolutionalTransformer#21]
Hey,

I can see that you provide a docker image, but is there a possibility that you provide a requirements file?

Best regards,
Benedikt

**Comment by Thanos-DB** [comment]
Hi @staniPetrox 

you can use 
https://gla-my.sharepoint.com/:f:/g/personal/a_tragakis_1_research_gla_ac_uk/EpyRwXVsbXxEmTaEjl-OuFYBQBuNkz9TfRP3DFR5WUf0jg?e=abEu7d

BR
Thanos

**Comment by staniPetrox** [comment]
Hey Thanos,

this doesn't work. You need to be a Glasgow faculty member to log in as I understand? Can we do this in another way?

Thank you and all the best,
Benedikt

**Comment by Thanos-DB** [comment]
Hi @staniPetrox 

it should be fixed now but just in case this is the content of the file

tensorflow==2.5.0
keras==2.8.0 
matplotlib==3.3.2 
medpy==0.4.0 
nibabel==3.2.1 
opencv-python 
pandas==1.1.3 
pydicom==2.2.2 
scikit-image 
scikit-learn

BR
Thanos

**Comment by recharladivyareddy** [comment]
Hello sir,
tensorflow 2.5 version isn't available

and if I use version 2.8
I'm getting this error.
Traceback (most recent call last):
  File "/content/FullyConvolutionalTransformer/TensorFlow/main.py", line 9, in <module>
    acdc_data, train_afn, train_hdr = get_acdc(acdc_data_train)
  File "/content/FullyConvolutionalTransformer/TensorFlow/utils.py", line 586, in get_acdc
    data[0] = np.expand_dims(data[0], axis=3)
  File "<__array_function__ internals>", line 180, in expand_dims
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/numeric.py", line 1397, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/numeric.py", line 1397, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 3 is out of bounds for array of dimension 2

thank you
